const PDFDocument = require('pdfkit');

/**
 * Generate a PDF report for job matching results
 */
function generateJobReport(job, matches, stream) {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    doc.pipe(stream);

    // Header
    doc.fontSize(22).font('Helvetica-Bold').text('SkillSense — Matching Report', { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').fillColor('#666')
        .text(`Generated on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, { align: 'center' });
    doc.moveDown(1);

    // Job Info Box
    doc.fillColor('#000').fontSize(14).font('Helvetica-Bold').text(`Job: ${job.title}`);
    if (job.company) doc.fontSize(10).font('Helvetica').text(`Company: ${job.company}`);
    doc.fontSize(10).font('Helvetica').fillColor('#666')
        .text(`Total Candidates Matched: ${matches.length}`);
    if (matches.length > 0) {
        const avg = Math.round(matches.reduce((s, m) => s + (m.scores?.final || 0), 0) / matches.length);
        doc.text(`Average Match Score: ${avg}%`);
    }
    doc.moveDown(1);

    // Divider
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#ddd').stroke();
    doc.moveDown(1);

    // Rankings Table
    doc.fillColor('#000').fontSize(14).font('Helvetica-Bold').text('Candidate Rankings');
    doc.moveDown(0.5);

    // Table Header
    const tableTop = doc.y;
    doc.fontSize(9).font('Helvetica-Bold').fillColor('#444');
    doc.text('Rank', 50, tableTop, { width: 35 });
    doc.text('Candidate', 90, tableTop, { width: 150 });
    doc.text('Score', 250, tableTop, { width: 45 });
    doc.text('Skills', 300, tableTop, { width: 45 });
    doc.text('Exp.', 350, tableTop, { width: 45 });
    doc.text('Semantic', 400, tableTop, { width: 55 });
    doc.text('Status', 465, tableTop, { width: 80 });
    doc.moveDown(0.3);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#eee').stroke();
    doc.moveDown(0.3);

    // Table Rows
    matches.forEach((match, idx) => {
        if (doc.y > 720) {
            doc.addPage();
        }

        const y = doc.y;
        const rank = idx + 1;
        const tierEmoji = rank <= 3 ? ['🥇', '🥈', '🥉'][rank - 1] : `#${rank}`;

        doc.fontSize(9).font('Helvetica').fillColor('#000');
        doc.text(tierEmoji, 50, y, { width: 35 });
        doc.text(match.candidateName || 'Unknown', 90, y, { width: 150 });
        doc.font('Helvetica-Bold').text(`${Math.round(match.scores?.final || 0)}%`, 250, y, { width: 45 });
        doc.font('Helvetica').text(`${Math.round(match.scores?.skillMatch || 0)}%`, 300, y, { width: 45 });
        doc.text(`${Math.round(match.scores?.experience || 0)}%`, 350, y, { width: 45 });
        doc.text(`${Math.round(match.scores?.semantic || 0)}%`, 400, y, { width: 55 });

        const status = match.status || 'pending';
        const statusColor = status === 'shortlisted' ? '#16a34a' : status === 'rejected' ? '#dc2626' : '#6b7280';
        doc.fillColor(statusColor).text(status.charAt(0).toUpperCase() + status.slice(1), 465, y, { width: 80 });

        doc.moveDown(0.6);
    });

    // Footer
    doc.moveDown(2);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#ddd').stroke();
    doc.moveDown(0.5);
    doc.fontSize(8).font('Helvetica').fillColor('#999')
        .text('This report was generated by SkillSense AI-Powered Recruitment Platform.', { align: 'center' });

    doc.end();
    return doc;
}

/**
 * Generate a one-page PDF summary for a single resume
 */
function generateResumeSummary(resume, stream) {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    doc.pipe(stream);

    // Header
    doc.fontSize(22).font('Helvetica-Bold').text('Candidate Profile Summary', { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').fillColor('#666')
        .text(`SkillSense Report — ${new Date().toLocaleDateString()}`, { align: 'center' });
    doc.moveDown(1.5);

    // Name
    doc.fillColor('#000').fontSize(18).font('Helvetica-Bold')
        .text(resume.candidateName || 'Unknown Candidate');
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').fillColor('#666')
        .text(`File: ${resume.fileName} | Uploaded: ${new Date(resume.uploadedAt).toLocaleDateString()}`);
    doc.moveDown(1);

    // Credibility
    if (resume.credibility?.score !== undefined) {
        doc.fontSize(12).font('Helvetica-Bold').fillColor('#000').text('Credibility Score');
        doc.fontSize(10).font('Helvetica').fillColor('#666')
            .text(`${resume.credibility.score}/100 — ${resume.credibility.level || 'N/A'}`);
        doc.moveDown(1);
    }

    // Skills
    const skills = resume.profile?.skills || [];
    if (skills.length > 0) {
        doc.fontSize(12).font('Helvetica-Bold').fillColor('#000').text('Skills');
        doc.moveDown(0.3);
        doc.fontSize(9).font('Helvetica').fillColor('#333');

        const grouped = skills.reduce((acc, s) => {
            const cat = s.category || 'other';
            if (!acc[cat]) acc[cat] = [];
            acc[cat].push(s.name);
            return acc;
        }, {});

        Object.entries(grouped).forEach(([cat, names]) => {
            doc.font('Helvetica-Bold').text(`${cat.toUpperCase()}: `, { continued: true });
            doc.font('Helvetica').text(names.join(', '));
        });
        doc.moveDown(1);
    }

    // Experience
    const experience = resume.profile?.experience || [];
    if (experience.length > 0) {
        doc.fontSize(12).font('Helvetica-Bold').fillColor('#000').text('Experience');
        doc.moveDown(0.3);
        experience.forEach(exp => {
            doc.fontSize(9).font('Helvetica-Bold').fillColor('#333')
                .text(`${exp.title || 'Role'}`, { continued: true });
            doc.font('Helvetica').text(` at ${exp.company || 'Company'}${exp.years ? ` (${exp.years} yrs)` : ''}`);
        });
        doc.moveDown(1);
    }

    // Education
    const education = resume.profile?.education || [];
    if (education.length > 0) {
        doc.fontSize(12).font('Helvetica-Bold').fillColor('#000').text('Education');
        doc.moveDown(0.3);
        education.forEach(edu => {
            doc.fontSize(9).font('Helvetica').fillColor('#333')
                .text(`${edu.level || 'Degree'} in ${edu.field || 'N/A'}${edu.institution ? ` — ${edu.institution}` : ''}`);
        });
        doc.moveDown(1);
    }

    // Summary
    if (resume.profile?.summary) {
        doc.fontSize(12).font('Helvetica-Bold').fillColor('#000').text('Summary');
        doc.moveDown(0.3);
        doc.fontSize(9).font('Helvetica').fillColor('#444').text(resume.profile.summary);
    }

    // Footer
    doc.moveDown(2);
    doc.fontSize(8).font('Helvetica').fillColor('#999')
        .text('Generated by SkillSense AI-Powered Recruitment Platform', { align: 'center' });

    doc.end();
    return doc;
}

module.exports = { generateJobReport, generateResumeSummary };
